# 🐧Please note that this file has been modified by Tencent on 2026/02/13. All Tencent Modifications are Copyright (C) 2026 Tencent.
from .api import (
    FewShotLoRAConv,
    LoRAConfig,
    LoRAConfigBuilder,
    LoRADetectionModel,
    ManualLoRAConv,
    PEFT_AVAILABLE,
    PeftModel,
    PeftProxy,
    _apply_rtdetr_lora_safety,
    _clear_lora_runtime_state,
    _collect_fallback_adapter_state,
    _get_mps_memory,
    _is_adapter_param,
    _load_fallback_adapter_state,
    _merge_manual_lora_conv,
    _merge_fallback_modules,
    _unfreeze_detection_head,
    _wrap_top_level_lora_model,
    apply_lora,
    get_lora_param_groups,
    resolve_adalora_total_step,
    resolve_effective_lora_request,
    select_lora_backend,
    supports_fallback_request,
    supports_peft_request,
)
from .io import _find_original_model_class, load_lora_adapters, merge_lora_weights, save_lora_adapters
from .training import LoraTrainingStrategy, get_lora_training_stats, suggest_lora_config_for_dataset

__all__ = [
    "PEFT_AVAILABLE",
    "PeftModel",
    "PeftProxy",
    "LoRAConfig",
    "LoRAConfigBuilder",
    "LoRADetectionModel",
    "FewShotLoRAConv",
    "ManualLoRAConv",
    "apply_lora",
    "get_lora_param_groups",
    "resolve_adalora_total_step",
    "resolve_effective_lora_request",
    "select_lora_backend",
    "save_lora_adapters",
    "load_lora_adapters",
    "merge_lora_weights",
    "LoraTrainingStrategy",
    "get_lora_training_stats",
    "suggest_lora_config_for_dataset",
    "supports_peft_request",
    "supports_fallback_request",
    "_apply_rtdetr_lora_safety",
    "_clear_lora_runtime_state",
    "_collect_fallback_adapter_state",
    "_find_original_model_class",
    "_get_mps_memory",
    "_is_adapter_param",
    "_load_fallback_adapter_state",
    "_merge_fallback_modules",
    "_merge_manual_lora_conv",
    "_unfreeze_detection_head",
    "_wrap_top_level_lora_model",
]
